@api-service = 127.0.0.1:5400

### List Feeds
GET http://{{api-service}}/api/feeds

### Remove item from Watch feed
#DELETE http://{{api-service}}/api/feeds/{id}

### Add Azure roadmap
POST http://{{api-service}}/api/feeds
Content-Type: application/json

{
    "url": "https://azure.microsoft.com/en-us/roadmap/feed/"
}

### Add item to Watch feed
POST http://{{api-service}}/api/feeds
Content-Type: application/json

{
    "url": "https://devblogs.microsoft.com/dotnet/feed/"
}