@crawler-service = 127.0.0.1:5100
@list-service = 127.0.0.1:5200
@resources-service = 127.0.0.1:5300

@url = https://devblogs.microsoft.com/dotnet/feed/

@feed-id = c50f7543-6b69-5e46-ae5e-bf0b82dede0e

### Add item to Watch List
POST http://{{list-service}}/api/list
Content-Type: application/json

{
    "url": "{{url}}"
}

### Get resource
GET http://{{resources-service}}/api/resources/1b5b03f0-a2bf-599c-b149-46dd72c5a134


### Get Watch List
GET http://{{list-service}}/api/list

### Get item from Watch List
GET http://{{list-service}}/api/list/{{feed-id}}

### Remove item from Watch List
DELETE http://{{list-service}}/api/list/{{feed-id}}



### Get Subscriptions
GET http://{{list-service}}/dapr/subscribe
