@feed-service-daprhttp = localhost:3500 

### post resource feed update event (reset)
POST http://{{feed-service-daprhttp}}/v1.0/publish/resource-feed-updates
Content-Type: application/json

{
    "url":"/api/resources/740f3d2f-2eb2-50e4-b695-aeed86dfe674",
    "id":"740f3d2f-2eb2-50e4-b695-aeed86dfe674",
    "lastCrawled":"2020-06-16T20:36:52.515943+00:00",
    "lastStatusCode":200,
    "type":1,
    "event":"update"
}


### Get Watch feed
GET http://{{feed-service-daprhttp}}/v1.0/invoke/feeds/method/api/feeds


### List Resources
GET http://{{feed-service-daprhttp}}/v1.0/invoke/feeds/method/api/resources/2020/06/30
### List Resources
GET http://{{feed-service-daprhttp}}/v1.0/invoke/feeds/method/api/resources/2020/07/06
### List Resources
GET http://{{feed-service-daprhttp}}/v1.0/invoke/feeds/method/api/resources/2020/07/07
### List Resources
GET http://{{feed-service-daprhttp}}/v1.0/invoke/feeds/method/api/resources/2020/07/08